using System.IO;
using UnityEditor;
using UnityEngine;

namespace ContentRepo.Editor
{
    public static class ContentManifestCodeGenerator
    {
        private const string FileName = "ContentManifestConfig.g.cs";

        public static void Generate()
        {
            var settings = ContentManifestCodeGenSettings.instance;
            var generation = ContentRepoGenerationSettings.instance.Generation;
            var outputFolder = settings.GeneratedOutputFolder;
            var uploadSettings = ContentUploadSettings.instance;
            var baseUrl = uploadSettings.CloudFrontDomain;
            var stagingPrefix = uploadSettings.StagingPrefix;
            var productionPrefix = uploadSettings.ProductionPrefix;

            var code = $@"// <auto-generated>
// This file was generated by ContentManifestCodeGenerator.
// Do not edit manually. Re-generate via Project Settings > Content Repo > Code Gen.
// </auto-generated>
using System.Threading;
using System.Threading.Tasks;
using ContentRepo;

public static class ContentManifestConfig
{{
    public const string BaseUrl = ""{baseUrl}"";
    public const string Generation = ""{generation}"";
    public const string StagingPrefix = ""{stagingPrefix}"";
    public const string ProductionPrefix = ""{productionPrefix}"";

    public static Task<ContentManifest> FetchAsync(ContentEnvironment env, CancellationToken ct = default)
    {{
        var envStr = env == ContentEnvironment.Staging ? StagingPrefix : ProductionPrefix;
        return ContentManifestClient.FetchAsync(BaseUrl, envStr, Generation, ct);
    }}
}}
";

            if (!Directory.Exists(outputFolder))
                Directory.CreateDirectory(outputFolder);

            var filePath = Path.Combine(outputFolder, FileName);
            File.WriteAllText(filePath, code);
            AssetDatabase.Refresh();
            Debug.Log($"[ContentRepo] Generated {filePath}");
        }
    }

    [InitializeOnLoad]
    internal static class ContentManifestCodeGenWatcher
    {
        private static string _lastGeneration;

        static ContentManifestCodeGenWatcher()
        {
            var genSettings = ContentRepoGenerationSettings.instance;
            genSettings.hideFlags &= ~HideFlags.NotEditable;
            _lastGeneration = genSettings.Generation;
            EditorApplication.update += OnEditorUpdate;
        }

        private static void OnEditorUpdate()
        {
            var current = ContentRepoGenerationSettings.instance.Generation;
            if (current == _lastGeneration) return;
            _lastGeneration = current;
            ContentManifestCodeGenerator.Generate();
        }
    }
}
